import os
import requests
from dotenv import load_dotenv

load_dotenv()

HF_API_TOKEN = os.getenv("HF_API_TOKEN")

# Hugging Face hosted model for AI-generated text detection
AI_DETECTOR_MODEL = "openai-community/roberta-base-openai-detector"
AI_DETECTOR_URL = f"https://router.huggingface.co/hf-inference/models/{AI_DETECTOR_MODEL}"

HEADERS = {"Authorization": f"Bearer {HF_API_TOKEN}"}


def query_ai_detector(text):
    """
    Send text to the Hugging Face-hosted RoBERTa OpenAI detector model.
    Returns classification labels and scores.
    """
    payload = {
        "inputs": text[:512],  # Model has a 512-token context window
        "options": {"wait_for_model": True}
    }
    try:
        response = requests.post(AI_DETECTOR_URL, headers=HEADERS, json=payload, timeout=30)
        response.raise_for_status()
        return response.json()
    except Exception as e:
        print(f"[Warn] AI detector API call failed: {e}")
        return None


def calculate_burstiness(text):
    """
    Calculate burstiness: the variation in sentence lengths.
    Human writing tends to have high burstiness (mix of short and long sentences).
    AI writing tends to have low burstiness (uniform sentence lengths).
    Returns a score between 0.0 (uniform/AI-like) and 1.0 (varied/human-like).
    """
    sentences = [s.strip() for s in text.split('.') if len(s.strip()) > 5]
    if len(sentences) < 2:
        return 0.5  # Not enough data

    lengths = [len(s.split()) for s in sentences]
    mean_len = sum(lengths) / len(lengths)
    variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
    std_dev = variance ** 0.5

    # Normalize: std_dev of 0 = AI-like, std_dev > 8 = very human-like
    burstiness = min(std_dev / 8.0, 1.0)
    return round(burstiness, 3)


def detect_ai_content(text):
    """
    Analyze text to determine the probability it was generated by AI.
    Uses HuggingFace's hosted RoBERTa model + burstiness scoring.
    Returns a dict with ai_probability (0-100), burstiness, and verdict.
    """
    burstiness = calculate_burstiness(text)

    # Call the Hugging Face API
    api_result = query_ai_detector(text)

    if api_result is None:
        return {
            "ai_probability": 0,
            "perplexity": None,
            "burstiness": burstiness,
            "verdict": "unknown"
        }

    # Parse the RoBERTa detector output
    # The model returns labels like "LABEL_0" (Real/Human) and "LABEL_1" (Fake/AI)
    ai_score = 0
    try:
        # The API returns [[{label, score}, {label, score}]]
        labels = api_result[0] if isinstance(api_result[0], list) else api_result
        for item in labels:
            label = item.get("label", "")
            score = item.get("score", 0)
            # "LABEL_1" = Fake/AI-generated, "LABEL_0" = Real/Human
            # Some versions use "Fake"/"Real" directly
            if label in ["LABEL_1", "Fake"]:
                ai_score = score
    except Exception as e:
        print(f"[Warn] Failed to parse AI detector response: {e}")
        ai_score = 0

    # Combine RoBERTa score (70%) with burstiness (30%)
    burst_component = max(0, (1.0 - burstiness)) * 100
    ai_probability = round(ai_score * 100 * 0.7 + burst_component * 0.3, 1)
    ai_probability = max(0, min(100, ai_probability))

    # Verdict
    if ai_probability > 70:
        verdict = "likely_ai"
    elif ai_probability > 40:
        verdict = "mixed"
    else:
        verdict = "likely_human"

    return {
        "ai_probability": ai_probability,
        "perplexity": None,  # We no longer use perplexity; RoBERTa is more accurate
        "burstiness": burstiness,
        "verdict": verdict
    }


# Quick test
if __name__ == "__main__":
    human_text = "I woke up late today. The rain was hammering against my window. I made coffee, burnt some toast, and sat there wondering if life had any meaning. Then my cat knocked over a glass. Typical."
    ai_text = "Artificial intelligence has revolutionized the way we process and analyze data in modern computing systems. Machine learning algorithms are trained on large datasets to identify patterns and make predictions with high accuracy."

    print("--- Human Text ---")
    result = detect_ai_content(human_text)
    print(f"  AI Probability: {result['ai_probability']}%")
    print(f"  Burstiness: {result['burstiness']}")
    print(f"  Verdict: {result['verdict']}")

    print("\n--- AI-like Text ---")
    result = detect_ai_content(ai_text)
    print(f"  AI Probability: {result['ai_probability']}%")
    print(f"  Burstiness: {result['burstiness']}")
    print(f"  Verdict: {result['verdict']}")
