import math
import torch
from transformers import GPT2LMHeadModel, GPT2TokenizerFast

# Load GPT-2 model for perplexity-based AI detection (downloads once)
print("[Info] Loading GPT-2 model for AI content detection...")
gpt2_model = GPT2LMHeadModel.from_pretrained("openai-community/gpt2")
gpt2_tokenizer = GPT2TokenizerFast.from_pretrained("openai-community/gpt2")
gpt2_model.eval()
print("[Info] GPT-2 model loaded successfully.")


def calculate_perplexity(text):
    """
    Calculate the perplexity of a text using GPT-2.
    Low perplexity = text is predictable = likely AI-generated.
    High perplexity = text is surprising = likely human-written.
    """
    try:
        encodings = gpt2_tokenizer(text, return_tensors="pt", truncation=True, max_length=512)
        input_ids = encodings.input_ids

        with torch.no_grad():
            outputs = gpt2_model(input_ids, labels=input_ids)
            loss = outputs.loss

        return math.exp(loss.item())
    except Exception as e:
        print(f"[Warn] Perplexity calculation failed: {e}")
        return None


def calculate_burstiness(text):
    """
    Calculate burstiness: the variation in sentence lengths.
    Human writing tends to have high burstiness (mix of short and long sentences).
    AI writing tends to have low burstiness (uniform sentence lengths).
    Returns a score between 0.0 (uniform/AI-like) and 1.0 (varied/human-like).
    """
    sentences = [s.strip() for s in text.split('.') if len(s.strip()) > 5]
    if len(sentences) < 2:
        return 0.5  # Not enough data

    lengths = [len(s.split()) for s in sentences]
    mean_len = sum(lengths) / len(lengths)
    variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
    std_dev = variance ** 0.5

    # Normalize: std_dev of 0 = AI-like, std_dev > 8 = very human-like
    burstiness = min(std_dev / 8.0, 1.0)
    return round(burstiness, 3)


def detect_ai_content(text):
    """
    Analyze text to determine the probability it was generated by AI.
    Combines perplexity analysis with burstiness scoring.
    Returns a dict with ai_probability (0-100), perplexity, burstiness, and verdict.
    """
    perplexity = calculate_perplexity(text)
    burstiness = calculate_burstiness(text)

    if perplexity is None:
        return {
            "ai_probability": 0,
            "perplexity": None,
            "burstiness": burstiness,
            "verdict": "unknown"
        }

    # --- Scoring Logic ---
    # Perplexity component (weight: 70%)
    # PPL < 30: very likely AI (score ~90-100)
    # PPL 30-60: possibly AI (score ~50-80)
    # PPL 60-120: mixed / uncertain (score ~20-50)
    # PPL > 120: likely human (score ~0-20)
    if perplexity < 30:
        ppl_score = 95
    elif perplexity < 60:
        ppl_score = 90 - ((perplexity - 30) / 30) * 40  # 90 -> 50
    elif perplexity < 120:
        ppl_score = 50 - ((perplexity - 60) / 60) * 30  # 50 -> 20
    else:
        ppl_score = max(0, 20 - ((perplexity - 120) / 100) * 20)  # 20 -> 0

    # Burstiness component (weight: 30%)
    # Low burstiness (< 0.3) = AI-like, high burstiness (> 0.6) = human-like
    burst_score = max(0, (1.0 - burstiness) * 100)

    # Combined weighted score
    ai_probability = round(ppl_score * 0.7 + burst_score * 0.3, 1)
    ai_probability = max(0, min(100, ai_probability))

    # Verdict
    if ai_probability > 70:
        verdict = "likely_ai"
    elif ai_probability > 40:
        verdict = "mixed"
    else:
        verdict = "likely_human"

    return {
        "ai_probability": ai_probability,
        "perplexity": round(perplexity, 2),
        "burstiness": burstiness,
        "verdict": verdict
    }


# Quick test
if __name__ == "__main__":
    human_text = "I woke up late today. The rain was hammering against my window. I made coffee, burnt some toast, and sat there wondering if life had any meaning. Then my cat knocked over a glass. Typical."
    ai_text = "Artificial intelligence has revolutionized the way we process and analyze data in modern computing systems. Machine learning algorithms are trained on large datasets to identify patterns and make predictions with high accuracy."

    print("--- Human Text ---")
    result = detect_ai_content(human_text)
    print(f"  AI Probability: {result['ai_probability']}%")
    print(f"  Perplexity: {result['perplexity']}")
    print(f"  Burstiness: {result['burstiness']}")
    print(f"  Verdict: {result['verdict']}")

    print("\n--- AI-like Text ---")
    result = detect_ai_content(ai_text)
    print(f"  AI Probability: {result['ai_probability']}%")
    print(f"  Perplexity: {result['perplexity']}")
    print(f"  Burstiness: {result['burstiness']}")
    print(f"  Verdict: {result['verdict']}")
